Netflix2/Controllers/AdminController.cs
using Netflix2.Models;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace Netflix2.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        XemPhimEntities database = new XemPhimEntities();
        // GET: Admin
        //Hiện thông tin các bộ Phim
        public ActionResult QuanLyPhim()
        {
            using (var dbContext = new XemPhimEntities())
            {
                var items = dbContext.Phims.ToList();

                return View(items);
            }
        }

        public ActionResult AddPhim(Phim phim)
        {
            if (ModelState.IsValid)
            {
                if (String.IsNullOrEmpty(phim.TenPhim) || phim.TenPhim.Length < 1 || phim.TenPhim.Length > 50)
                    ModelState.AddModelError(String.Empty, "Tên Phim không được để trống và phải có ít nhất 1 ký tự, không quá 50 ký tự");
                if (String.IsNullOrEmpty(phim.URLPhim))
                    ModelState.AddModelError(String.Empty, "Url không được để trống");
                if (String.IsNullOrEmpty(phim.HinhMinhHoa))
                    ModelState.AddModelError(String.Empty, "Hình minh họa không được để trống");
                if (String.IsNullOrEmpty(phim.ThoiLuong))
                    ModelState.AddModelError(String.Empty, "Thời lượng không được để trống");         
                else
                {
                    if (!TimeSpan.TryParse(phim.ThoiLuong, out _))
                    {
                        ModelState.AddModelError("ThoiLuong", "Thời Lượng không hợp lệ. Hãy nhập giá trị kiểu thời gian đúng.");
                    }
                }
                if (ModelState.IsValid)
                {
                    database.Phims.Add(phim);
                    database.SaveChanges();
                }
                else
                {
                    return View();
                }
            }
            return RedirectToAction("QuanLyPhim");
        }
        public ActionResult SuaPhim(int Id)
        {
            XemPhimEntities database = new XemPhimEntities();
            Phim e = database.Phims.Where(i => i.IdPhim == Id).FirstOrDefault();

            database.Dispose();
            return View(e);
        }
        public ActionResult LuuPhim(Phim s)
        {
            XemPhimEntities database = new XemPhimEntities();
            Phim e = database.Phims.Where(i => i.IdPhim == s.IdPhim).FirstOrDefault();
            e.TieuDe = s.TieuDe;
            e.ChiTietPhim = s.ChiTietPhim;
            e.TenPhim = s.TenPhim;
            e.URLPhim = s.URLPhim;
            e.NamSanXuat = s.NamSanXuat;
            e.ChiTietPhim = s.ChiTietPhim;
            e.DaoDien = s.DaoDien;
            e.DienVien = s.DienVien;
            e.HinhMinhHoa = s.HinhMinhHoa;
            e.TheLoai = s.TheLoai;
            database.SaveChanges();
            database.Dispose();
            return Redirect("QuanLyPhim");
        }
        public ActionResult XoaPhim(int Id)
        {
            XemPhimEntities database = new XemPhimEntities();
            Phim e = database.Phims.Where(i => i.IdPhim == Id).FirstOrDefault();

            database.Dispose();
            return View(e);
        }
        public ActionResult XacNhanXoaPhim(Phim s)
        {
            XemPhimEntities database = new XemPhimEntities();
            Phim e = database.Phims.Where(i => i.IdPhim == s.IdPhim).FirstOrDefault();

            database.Phims.Remove(e);
            database.SaveChanges();
            database.Dispose();
            return Redirect("QuanLyPhim");
        }
        public ActionResult QuanLyUser()
        {
            using (var dbContext = new XemPhimEntities())
            {
                var items = dbContext.KhachHangs.ToList();

                return View(items);
            }
        }
        public ActionResult AddUser(KhachHang khachHang)
        {
            if (ModelState.IsValid)
            {
                var existingEmail = database.KhachHangs.FirstOrDefault(k => k.Email == khachHang.Email);
                if (existingEmail != null)
                {
                    ModelState.AddModelError(String.Empty, "Địa chỉ Email đã được sử dụng, vui lòng chọn địa chỉ Email khác.");
                }
                if (String.IsNullOrEmpty(khachHang.TenDangNhap) || khachHang.TenDangNhap.Length < 1 || !Regex.IsMatch(khachHang.TenDangNhap, "^[a-zA-Z0-9 ]*$"))
                {
                    ModelState.AddModelError(String.Empty, "Tên Đăng Nhập không hợp lệ");
                }

                if (String.IsNullOrEmpty(khachHang.HoTenKH) || khachHang.HoTenKH.Length < 1 )
                {
                    ModelState.AddModelError(String.Empty, "Họ Và Tên không hợp lệ");
                }

                if (String.IsNullOrEmpty(khachHang.Email) || !Regex.IsMatch(khachHang.Email, @"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"))
                {
                    ModelState.AddModelError(String.Empty, "Email không hợp lệ");
                }

                if (String.IsNullOrEmpty(khachHang.MatKhau))
                {
                    ModelState.AddModelError(String.Empty, "Mật Khẩu không được để trống");
                }

                if (ModelState.IsValid)
                {
                    database.KhachHangs.Add(khachHang);
                    database.SaveChanges();
                    return RedirectToAction("QuanLyUser");
                }
            }

            // Nếu ModelState không hợp lệ, quay lại view để hiển thị lỗi
            return View();
        }
        public ActionResult SuaUser(int Id)
        {
            XemPhimEntities database = new XemPhimEntities();
            KhachHang e = database.KhachHangs.Where(i => i.MaKH == Id).FirstOrDefault();

            if (e != null)
            {
                // Kiểm tra hợp lệ cho email, họ tên và tên đăng nhập
                if (String.IsNullOrEmpty(e.TenDangNhap) || e.TenDangNhap.Length < 1 || !Regex.IsMatch(e.TenDangNhap, "^[a-zA-Z0-9 ]*$"))
                {
                    ModelState.AddModelError(String.Empty, "Tên Đăng Nhập không hợp lệ");
                }

                if (String.IsNullOrEmpty(e.HoTenKH) || e.HoTenKH.Length < 1)
                {
                    ModelState.AddModelError(String.Empty, "Họ Và Tên không hợp lệ");
                }

                if (String.IsNullOrEmpty(e.Email) || !e.Email.EndsWith("@gmail.com", StringComparison.OrdinalIgnoreCase))
                {
                    ModelState.AddModelError(String.Empty, "Email không hợp lệ. Vui lòng nhập lại email");
                }

                return View(e);
            }

            database.Dispose();
            return RedirectToAction("QuanLyUser");
        }

        public ActionResult LuuUser(KhachHang s)
        {
            XemPhimEntities database = new XemPhimEntities();
            KhachHang e = database.KhachHangs.Where(i => i.MaKH == s.MaKH).FirstOrDefault();
            e.TenDangNhap = s.TenDangNhap;
            e.HoTenKH = s.HoTenKH;
            e.MatKhau = s.MatKhau;
            e.Email = s.Email;

            database.SaveChanges();
            database.Dispose();
            return Redirect("QuanLyUser");
        }
        public ActionResult XoaUser(int Id)
        {
            XemPhimEntities database = new XemPhimEntities();
            KhachHang e = database.KhachHangs.Where(i => i.MaKH == Id).FirstOrDefault();

            database.Dispose();
            return View(e);
        }
        public ActionResult XacNhanXoaUser(KhachHang s)
        {
            XemPhimEntities database = new XemPhimEntities();
            KhachHang e = database.KhachHangs.Where(i => i.MaKH == s.MaKH).FirstOrDefault();

            database.KhachHangs.Remove(e);
            database.SaveChanges();
            database.Dispose();
            return Redirect("QuanLyUser");
        }
    }
}

Netflix2/Controllers/NguoiDungController.cs
using Netflix2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace Netflix2.Controllers
{
    public class NguoiDungController : Controller
    {
        // GET: NguoiDung
        XemPhimEntities database = new XemPhimEntities();
        XemPhimEntities UserDataBase = new XemPhimEntities();
        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }
        public ActionResult DangKy()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangKy(KhachHang kh)
        {
            if (ModelState.IsValid)
            {
                if (String.IsNullOrEmpty(kh.HoTenKH))
                    ModelState.AddModelError(String.Empty, "Họ tên không được để trống");
                if (String.IsNullOrEmpty(kh.TenDangNhap))
                    ModelState.AddModelError(String.Empty, "Tên đăng nhập không được để trống");
                if (String.IsNullOrEmpty(kh.MatKhau))
                    ModelState.AddModelError(String.Empty, "Mật Khẩu không được để trống");;
                if (String.IsNullOrEmpty(kh.Email))
                    ModelState.AddModelError(String.Empty, "Email không được để trống");
                if (kh.MatKhau.Length < 6)
                    ModelState.AddModelError(string.Empty, "Mật Khẩu không được ít hơn 6 ký tự");

                var khachhang = database.KhachHangs.FirstOrDefault(k => k.TenDangNhap== kh.TenDangNhap);
                if (khachhang != null)
                    ModelState.AddModelError(string.Empty, "Đã có người đăng ký tên này");
                var khEmail = database.KhachHangs.FirstOrDefault(k => k.Email == kh.Email);
                if (khEmail != null)
                    ModelState.AddModelError(string.Empty, "Đã có người đăng ký Email này");
                else if (!kh.Email.EndsWith("@gmail.com", StringComparison.OrdinalIgnoreCase))
                    ModelState.AddModelError(string.Empty, "Email phải kết thúc bằng @gmail.com");

                if (ModelState.IsValid)
                {
                    database.KhachHangs.Add(kh);
                    database.SaveChanges();
                }
                else
                {
                    return View();
                }
            }
            return RedirectToAction("DangNhap");
        }

        public ActionResult DangNhap(KhachHang kh)
        {
            if (ModelState.IsValid)
            {
                if (string.IsNullOrEmpty(kh.TenDangNhap))
                    ModelState.AddModelError(string.Empty, "Tên đăng nhập không được để trống");
                if (string.IsNullOrEmpty(kh.MatKhau))
                    ModelState.AddModelError(string.Empty, "Mật khẩu không được để trống");
                if (kh.TenDangNhap == "Admin" && kh.MatKhau == "Admin")
                    return RedirectToAction("QuanLyPhim", "Admin");
                if (ModelState.IsValid)
                {
                    var khach = database.KhachHangs.FirstOrDefault(k => k.TenDangNhap == kh.TenDangNhap && k.MatKhau == kh.MatKhau);
                    if (khach != null)
                    {
                        ViewBag.Thongbao = "Chúc mừng đăng nhập thành công";

                        Session["TaiKhoan"] = khach.TenDangNhap;
                        Session["MaKH"] = khach.MaKH;
                        // Dừng chương trình trong 3 giây
                        Thread.Sleep(3000);

                        // Chuyển hướng đến trang chủ
                        return RedirectToAction("TrangChu", "Home");

                    }
                    else
                        ViewBag.ThongBao = "Tên đăng nhập hoặc mật khẩu không đúng";
                }
            }
            return View();
        }

        public ActionResult ChiTietUser(string tkkh)
        {
            var User = UserDataBase.KhachHangs.FirstOrDefault(s => s.TenDangNhap == tkkh);
            return View(User);
        }

        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("TrangChu", "Home");
        }
        

    }
}

Netflix2/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Netflix Clone</title>
    <link rel="stylesheet" href="~/Content/AdminCSS/Admin.css" />
</head>
<body>
    <div class="headerAdmin">
        <div class="logo"><a class="logo" style="color: #e50914; font-size: 36px; font-weight: 800; margin-left: 20px;" href="~/Home/TrangChu">Netflix</a></div>
        <div class="nav">
            <a>@Html.ActionLink("Quản Lý Phim", "QuanLyPhim", "Admin")</a>
            <a>@Html.ActionLink("Quản Lý User", "QuanLyUser", "Admin")</a>
        </div>
    </div>
    <div>
        @RenderBody()
    </div>
    <footer>
        <div class="footer-links">
            <a href="#">Questions?</a>
            <a href="#">Help Center</a>
            <a href="#">Terms of Use</a>
            <a href="https://help.netflix.com/legal/privacy">Privacy</a>
            <a href="#">Cookie Preferences</a>
            <a href="#">Corporate Information</a>
            <a href="#">Contact Us</a>
            <a href="#">Speed Test</a>
            <a href="#">Legal Notices</a>
            <hr />
            <a href="#">Only on Netflix</a>
            <p>&copy; 2023 Netflix. All Rights Reserved</p>
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Netflix2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Netflix Clone</title>
    <link rel="stylesheet" href="~/Content/MainCSS/MainCS.css" />
</head>
<body>
    <div class="header">
        <div class="logo"><a class="logo" style="color: #e50914; font-size: 36px; font-weight: 800; margin-left: 20px;" href="~/Home/TrangChu">Netflix</a></div>
        <div class="nav">
            <a>@Html.ActionLink("Trang Chủ", "TrangChu", "Home")</a>
            <a>@Html.ActionLink("Tìm Kiếm", "TimKiem", "Home")</a>
        </div>
        @if (@Session["TaiKhoan"] == null)
        {
            <div class="login-buttons">
                <button class="login-button">@Html.ActionLink("Đăng Nhập", "DangNhap", "NguoiDung")</button>
                <button class="login-button">@Html.ActionLink("Đăng Ký", "DangKy", "NguoiDung")</button>
            </div>
        }
        else
        {
            <div class="login-buttons">
                <div class="login-button"><a href="@Url.Action("ChiTietUser", "NguoiDung", new { tkkh = Session["TaiKhoan"] })"><span class="glyphicon glyphicon-user"></span>@Session["TaiKhoan"]</a></div>
            </div>
        }
    </div>
    <div>
        @RenderBody()
    </div>
    <footer>
        <div class="footer-links">
            <a href="#">Questions?</a>
            <a href="#">Help Center</a>
            <a href="#">Terms of Use</a>
            <a href="https://help.netflix.com/legal/privacy">Privacy</a>
            <a href="#">Cookie Preferences</a>
            <a href="#">Corporate Information</a>
            <a href="#">Contact Us</a>
            <a href="#">Speed Test</a>
            <a href="#">Legal Notices</a>
            <hr />
            <a href="#">Only on Netflix</a>
            <p>&copy; 2023 Netflix. All Rights Reserved</p>
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>